services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ujwaldhakal\OpentracingMessengerBundle\EventSubscriber\SendMessageToTransportSubscriber: ~
  Ujwaldhakal\OpentracingMessengerBundle\EventSubscriber\WorkerMessageReceivedSubscriber: ~
  Ujwaldhakal\OpentracingMessengerBundle\EventSubscriber\WorkerMessageHandledSubscriber: ~
  Ujwaldhakal\OpentracingMessengerBundle\Tracing\TracingInterface:
    class: Ujwaldhakal\OpentracingMessengerBundle\Tracing\OpenTracing
